### ISSUE TITLE
Get extent parameter (corresponding to cluster-wise FWE p<0.05) automatically in SPM

### ISSUE THREAD

**Issue by cmaumet** [NISOx-BDI/Software_Comparison_Analyses#10]
Currently the group-level script of SPM has the cluster size corresponding to FWE p<0.05 cluster-wise thresholded hard-coded (to 171): https://github.com/AlexBowring/Software_Comparison/blob/master/scripts/lib/template_ds001_SPM_level2.m#L31. We might want to update this and get it from the corresponding SPM variable.

**Comment by AlexBowring** [comment]
We have agreed to leave this hard-coded. Closed
