### ISSUE TITLE
Need same axial slices for all views

### ISSUE THREAD

**Issue by nicholst** [NISOx-BDI/Software_Comparison_Analyses#18]
In https://github.com/AlexBowring/Software_Comparison/blob/master/ds001_notebook.ipynb line 17, we need to see the same slices for all three software packages.

**Comment by AlexBowring** [comment]
Thanks @nicholst, this change has been implemented

**Comment by nicholst** [comment]
Which branch?  Master still has the varying number of slices.  As I'm here with Russ Poldrack & co, it would be nice if I could show them a like-for-like comparisons.

**Comment by AlexBowring** [comment]
@nicholst comparisons, I will push what I have so far

**Comment by nicholst** [comment]
Got it... I now see it on the comparisons branch
