### ISSUE TITLE
Take into account number of discarded fMRI volumes 

### ISSUE THREAD

**Issue by cmaumet** [NISOx-BDI/Software_Comparison_Analyses#2]
Currently it is assumed that `4s` have to be discarded from the onsets in [create_onset_files.m](
https://github.com/AlexBowring/Software_Comparison/blob/master/scripts/lib/create_onset_files.m#L72) but in practice, this parameter should be allowed to vary across studies. 

We could solve this by creating a new variable in [process_ds001.m](https://github.com/AlexBowring/Software_Comparison/blob/master/scripts/process_ds001.m) to set the number of volumes that must be discarded. This variable will need to be passed to 
 - `create_onset_files.m` where it will be combined to the TR to get the shift in seconds
 - `run_subject_level_analyses.m` to ignore the first fmri volumes in the selection.

**Comment by AlexBowring** [comment]
Do you agree that this should actually be two variables? One with the number of volumes that need to be deleted (in ds001 this is 2) and then the time removed when using BIDSto3col, which is equal to the number of volumes \* TR (in ds001 this is 4s).

**Comment by cmaumet** [comment]
Yes. Ideally, I thought we could get the TR from BIDS but I could not locate it for ds001 so I think it is fine to create two variables for now.
