### ISSUE TITLE
In Bland-Altman scatter plots, deal with overplotting better

### ISSUE THREAD

**Issue by nicholst** [NISOx-BDI/Software_Comparison_Analyses#20]
To deal with the severe overplotting you can (1) make the points smaller, and/or (2) make the points transparent (maybe with this option ?  `alpha=0.2`?)

Also, it's a minor stylistic thing, but for best visualization I find the outline on plotting symbols a distraction (i.e. *either* plot with open circles, *or* plot solid circles, but not both).  (`edgecolors='none'`?)

**Comment by AlexBowring** [comment]
We dealt with this now. Lets close the issue.
