### ISSUE TITLE
Single NeuroVault collection for all NIDM packs?

### ISSUE THREAD

**Issue by cmaumet** [NISOx-BDI/Software_Comparison_Analyses#24]
Could we have a single collection with all the NIDM packs rather than a separate one per study? We could use a naming convention like `<studyName>_<softwareName>.nidm.zip` (e.g. `ds000001_SPM.nidm.zip`, `ds000019_SPM.nidm.zip`...). 

It would make it easier to review the results interactively (only one NeuroVault page to open) and it should not be too much work to change the notebooks to take this into account. What do you think about this @AlexBowring?

**Comment by AlexBowring** [comment]
@cmaumet I would rather not have larger collections on Neurovault as it is slow to load up all the files. I also think this would make it harder to compare results from separate studies, as you have to sift out which are the correct results. It is also less easy to flexibly remove and upload new results (On neurovault I dont think you can order the files, newest ones are at the bottom). Then, we also have to study ID all the other files, changing file names which are outputted by the software. I also would have to change the notebook as right now it downloads all NIDM packs in the collection, to point at the packs for only that study. I actually think it would make it harder to review the results and is more inconvenient then having to open another webpage.

**Comment by cmaumet** [comment]
Okay that's fine. Though I think it would make sense to rename each NIDM pack with a more meaningful name (e.g. as the ones suggested above).

**Comment by AlexBowring** [comment]
@cmaumet Yes, I agree. We don't have NIDM export implemented into the main scripts atm (this is open in other issues)... so when I implement this I will study ID the packs.
