### ISSUE TITLE
Max value for colorscale should be an argument of `plot_excursion_sets` function

### ISSUE THREAD

**Issue by cmaumet** [NISOx-BDI/Software_Comparison_Analyses#28]
Hi @AlexBowring,

In the ds120 notebook: https://github.com/AlexBowring/Software_Comparison/blob/AFNI_2mm_voxels/ds120_notebook.ipynb, in the excursion set plots the blobs are mainly white (instead of varying from red to white in [ds001 notebook](https://github.com/AlexBowring/Software_Comparison/blob/master/ds001_notebook.ipynb)). 

It looks like, this is due to the fact that the maximum value of the colorscale is hardcoded to `4.2` in `plot_excursion_sets.py` (`vmax=4.2`):

https://github.com/AlexBowring/Software_Comparison/blob/9272e5a324701281a379a868f347a9f0bf70f3a9/scripts/lib/plot_excursion_sets.py#L25

Do you think you update `plot_excursion_sets.py` to have the max value of the colorscale as argument and set this appropriately for each study (I think `4.2` was the value for the first study we looked at)?

Let me know if you need more info.

**Comment by AlexBowring** [comment]
Hi @cmaumet,

plot_excursion_sets now takes an argument max_activation which determines the max value of the color scale. I have also sets the color scales to be consistent with the figures in the publication. Are you happy for me to close this issue?

**Comment by cmaumet** [comment]
Sure! Did you push the code directly to master?

**Comment by AlexBowring** [comment]
Yes
