### ISSUE TITLE
TO DOS

### ISSUE THREAD

**Issue by cmaumet** [NISOx-BDI/Software_Comparison_Analyses#30]
This is a copy of former `TO DOS` file created by @AlexBowring:

 - [x] AFNI ds001: redo analysis; remember do level 2 with acf calculations and do euler characteristics 
 - [x] PERMUTATION TESTS IN AFNI FOR DS001, FSL FOR DS001, DS120.
 - [x] ds120 in AFNI SPM AND FSL, permutation tests. 

I add those items here so that all todos are available as issues at: https://github.com/AlexBowring/Software_Comparison/issues.

**Comment by AlexBowring** [comment]
@cmaumet Thanks for this... This text file was accidentally added to the commit :)

**Comment by cmaumet** [comment]
:) Github issues are a good way to track all those todos :)

**Comment by AlexBowring** [comment]
This is done, lets close the issue
