### ISSUE TITLE
Slice numbers to be displayed should be an argument of `plot_excursion_sets` function

### ISSUE THREAD

**Issue by cmaumet** [NISOx-BDI/Software_Comparison_Analyses#32]
Hi again @AlexBowring ,

Thanks for fixing  https://github.com/AlexBowring/Software_Comparison/issues/28.

Similarly to what you did for the max of the colorscale, do you think you could update `plot_excursion_sets.py` to have the slice coordinates as argument and set this appropriately for each study (I think `x=4 x=32 y=38` were the values for the first study we looked at)?

**Comment by AlexBowring** [comment]
@cmaumet Okay... Am I okay to push to master or would you rather i make new branches?

**Comment by cmaumet** [comment]
It's always good to make branches and PRs to keep track of changes... But master should be fine :)

**Comment by AlexBowring** [comment]
@cmaumet plot_excursion_sets.py now takes x_coords, y_coords, and z_coords as arguments for which axial slices to display in each dimension, and I have updated each of the notebooks. I did this on the branch slice_numbers. Are you okay for me to merge this to master and close this issue?

**Comment by cmaumet** [comment]
Yes! Looks great! I've created a PR as it's easier to review the changes. I've made a tiny comment over there :)
