### ISSUE TITLE
Missing "perm_Negative_clustered_t_stat.nii.gz" file for ds109

### ISSUE THREAD

**Issue by cmaumet** [NISOx-BDI/Software_Comparison_Analyses#48]
When rerunning the ds109 notebook, I get the following error:

![screen shot 2018-03-09 at 15 39 41](https://user-images.githubusercontent.com/5374264/37212791-5b5b9014-23b0-11e8-9a80-1e4f7fc5f204.png)

@AlexBowring: Can you upload `perm_Negative_clustered_t_stat.nii.gz` in the corresponding NeuroVault collection?

**Comment by AlexBowring** [comment]
@cmaumet : Thanks for reporting. That image doesn't exist for this study. This is a bug because I have used one function to download all the images for all of the studies. I need to add an if statement to the download_data.py function so it doesn't look for that image here.

**Comment by cmaumet** [comment]
Okay, good! Should I write this update so that you can focus on the manuscript?

**Comment by AlexBowring** [comment]
If you want to give it a try that is great... thinks get pretty nasty when you dive into that code though. Because different studies have different images missing it can get ugly trying to make it work for all notebooks.

**Comment by AlexBowring** [comment]
@cmaumet : The easiest way to do this might be to look at the old notebooks where I hadn't made this function. Then just add if statements in the download_data function such like
if "study" = 'ds001': *paste code that used to be in ds001 notebook*
if "study" = 'ds109': *past code that used to be in ds109 notebook*

does that make sense? If not I am happy to do it

**Comment by cmaumet** [comment]
I'll have a look now.

**Comment by cmaumet** [comment]
I've included a fix for this in #45 (https://github.com/AlexBowring/Software_Comparison/pull/45/commits/16fd96345921019ac84212495de6345595116916) but I would like to double check that it's not breaking anything for the other studies before we merge #45.

**Comment by cmaumet** [comment]
@AlexBowring: I am reopening this issue as this problem is also in ds120, with other files. 

Can you point me to a commit on GitHub that corresponds to "*paste code that used to be in ds001 notebook*" to help me find out which file is which?

**Comment by AlexBowring** [comment]
@cmaumet : Here is an old ds001 notebook which did not use an external function to download the data:
https://github.com/AlexBowring/Software_Comparison/blob/04f54770e9739a0eb263aa11e4231671057ed7ec/figures/ds001_notebook.ipynb

Let me know if that helps you find what you're looking for.

**Comment by cmaumet** [comment]
Thanks! I think I am almost done in #45.

The issue with `perm_Negative_clustered_t_stat.nii.gz` is now fixed by https://github.com/AlexBowring/Software_Comparison/pull/45/commits/b351f139d5c08ba33d46933df59a41c0321b9cd4 (as part of #45).
