### ISSUE TITLE
Add export to NIDM in FSL scripts

### ISSUE THREAD

**Issue by cmaumet** [NISOx-BDI/Software_Comparison_Analyses#5]
We should also add export to NIDM-Results in the FSL script. This can be done using `nidmfsl` as in https://github.com/incf-nidash/nidmresults-fsl/blob/master/test/export_test_battery.py#L118-L121 (a variable including info about the group will need to be created in the "master" script).

@AlexBowring: can you give this a go? Let me know how it goes!

**Comment by cmaumet** [comment]
@AlexBowring: is this somewhere in the repo now? If not can you create a script with the required calls to `nidmfsl` (I need to refer to it in the README)

**Comment by AlexBowring** [comment]
@cmaumet I have done this. There is now a nidm_export function in the fsl_processing.py script. Which gets called by the process_dsxxx_FSL.py master scripts. You may want to test this, otherwise I am happy to close the issue.

**Comment by cmaumet** [comment]
Let's close the issue.
