### ISSUE TITLE
Uncomment all commands in scripts

### ISSUE THREAD

**Issue by cmaumet** [NISOx-BDI/Software_Comparison_Analyses#51]
I'm working on the README, cf. #50 and looking at `process_ds001_SPM.m`, I've noticed that some of the commands are commented out, e.g.: https://github.com/AlexBowring/Software_Comparison/blob/master/scripts/process_ds001_SPM.m#L47-L51.

@AlexBowring: Can you have a pass over all the master script and uncomment when needed?

**Comment by AlexBowring** [comment]
I have done this, resolved
