### ISSUE TITLE
Missing "afni_spm_reslice_pos_exc.nii.gz" for ds120?

### ISSUE THREAD

**Issue by cmaumet** [NISOx-BDI/Software_Comparison_Analyses#53]
@AlexBowring, for ds120, I get the following error:

```
Exception: ['HTTP Error:404http://neurovault.org/media/images/2982/afni_spm_reslice_pos_exc.nii.gz']
```

but I thought the 'positive excursion set AFNI resliced on SPM image' should be present for ds120. Can you confirm whether this image is indeed missing from [NeuroVault collection 2982](neurovault.org/media/images/2982/) or if this file should be ignored for this study?
 Thanks!

**Comment by cmaumet** [comment]
I think I've found it: is this the one: [afni_spm_reslice_exc.nii.gz](https://neurovault.org/images/54121/)?

**Comment by AlexBowring** [comment]
Yes... good fine. ach! Thats another nasty thing... since there are no negative excursion sets for that study I just called it 'exc' rather than 'pos_exc'. This will need to be considered by the function for it to work.

**Comment by cmaumet** [comment]
Thanks! I am almost done with edits on the `download_data` function. I wil push everything to #45 when ready.
