### ISSUE TITLE
Error in ds001 notebook

### ISSUE THREAD

**Issue by cmaumet** [NISOx-BDI/Software_Comparison_Analyses#54]
Hi @AlexBowring,

There is an error message in the current version of the [ds109 notebook](https://github.com/AlexBowring/Software_Comparison/blob/master/figures/ds109_notebook.ipynb): 

<img width="692" alt="screen shot 2018-03-13 at 20 56 08" src="https://user-images.githubusercontent.com/5374264/37366538-ff156f2e-2700-11e8-8ffd-e2180d1f0ebe.png">

@AlexBowring: if you merge #45 and update the ds109 notebook you should get rid of this message. Let me know how this goes.

**Comment by AlexBowring** [comment]
Hi @cmaumet , It worked! Thank you! Issue closed

**Comment by cmaumet** [comment]
Great! Have you pushed the updates in the notebooks?

**Comment by AlexBowring** [comment]
@cmaumet I have now, thanks
