### ISSUE TITLE
Why do we use reaload?

### ISSUE THREAD

**Issue by nicholst** [NISOx-BDI/Software_Comparison_Analyses#55]
I notice on the ds001 notebook (maybe others) that we have the command

```
from lib import download_data
reload(download_data)
```

Why do we need the reload immediately following the import?  It doesn't seem to be necessary and will only cause confusion.

**Comment by cmaumet** [comment]
`reload` is useful when we are updating the code in our `lib` folder to make sure that the notebook refreshes all those functions. We can remove them although they could be useful for a newcomer trying to understand the code by making edits in the codebase.

**Comment by nicholst** [comment]
I think it will only add confusion, no?  I'd remove them (we don't use the
notebook to show all the iterative misteps and do-overs that we did to get
to the final result, no?)

**Comment by cmaumet** [comment]
We don't show all the misteps but if someone tries to update some parts of the code (which makes sense when trying to understand a piece of code) then the `reload` will help.

But I'm fine with removing them.

**Comment by AlexBowring** [comment]
Reloads are gone, resolved
