### ISSUE TITLE
README reproducing thresholded figures

### ISSUE THREAD

**Issue by cmaumet** [NISOx-BDI/Software_Comparison_Analyses#60]
@AlexBowring: in order to reproduce fig. 1, the README says "Same as Fig. 1, but using ./figures/ds109_notebook.ipynb and setting x_coords=[0, 32]."

Can we remove the `setting x_coords=[0, 32]` part? The selection of slices is already done in the notebook therefore a user will not have to set this up, right? If you really like to mention the exact slices, then we could say something like for the previous figure `in this cell, make sure that x_coords=[4, 32]`.

**Comment by AlexBowring** [comment]
@cmaumet : Its a bit awkward actually, because for Fig1 we set these x coordinates as [0, 32]... but for the permutation test coords its [4,32]. Its going to look strange in the notebook if they are not looking at the same slices, so atm they are both looking at [4,32]

**Comment by cmaumet** [comment]
In the notebook, we should really have the coordinate that we are using in the paper. That's the easiest way for someone else to reproduce our figures... Is this feasible with the current setup?

**Comment by AlexBowring** [comment]
Okay. Its all fixed up to be the same as manuscript figures... readme is also updated with 'make sure that' rather than 'setting'

**Comment by cmaumet** [comment]
Thanks!
